---
title: "prelim vis"
author: "devin"
date: "January 22, 2016"
output: html_document
---

```{r}
library(readr)
library(dplyr)
library(lubridate)
library(ggplot2)
library(PKPDmisc)
```

```{r}
jan <- read_csv("~/Desktop/january_stars.csv.gz") %>% select(-one_of("NA")) 
feb <- read_csv("~/Desktop/february_stars.csv.gz")%>% select(-one_of("NA")) 
march <- read_csv("~/Desktop/march_stars.csv.gz")%>% select(-one_of("NA")) 
```

```{r}
head(jan)
```

```{r}
months <- rbind(jan, feb)
months <- rbind(months, march)

temp <- head(months)


all_repo_stars <- march %>%
  group_by(repository, repo_owner) %>% 
  tally %>% 
  arrange(desc(n))
```

```{r}
more_than_ten <- all_repo_stars %>% # ~ 144000 repo owners
  ungroup %>% filter(n > 5)
more_than_ten %>% 
  select(repo_owner) %>% 
  group_by(repo_owner) %>% 
  tally
owners_with_mt1_repo_with_mt_ten_stars <- more_than_ten %>% 
  select(repo_owner) %>% 
  group_by(repo_owner) %>% 
  tally %>%  ## ~ 28000
  filter(n > 1) %>%## ~ 7000
  arrange(desc(n))
```

```{r}
more_than_five <- all_repo_stars %>% 
  ungroup %>% filter(n > 5)
more_than_five %>% 
  select(repo_owner) %>% 
  group_by(repo_owner) %>% 
  tally
more_than_five %>% 
  select(repo_owner) %>% 
  group_by(repo_owner) %>% 
  tally %>% 
  filter(n > 1) 
```

```{r}
all_repo_stars %>% 
  filter( n>10  , n < 200) %>% 
  ggplot(aes(x = n)) + geom_histogram(binwidth=1, fill = "white", color = "black") +
  theme_bw() + base_theme() +
  labs(x = "Number of stars")
```

```{r}
selfies <- months %>% 
  filter(starer == repo_owner) 

not_selfies <- months %>% 
  filter(starer != repo_owner) %>%
    group_by(repository) %>% 
  tally %>% 
  arrange(desc(n))

head(not_selfies)
selfies
selfie_count <- selfies %>% group_by(repository) %>% 
  tally %>% 
  arrange(desc(n)) %>% 
  rename(num_stars = n) %>% group_by(num_stars) %>% tally

all_count <- all_repo_stars %>% rename(num_stars = n) %>%
  group_by(num_stars) %>% tally

self_star1 <- all_repo_stars %>%
  filter(n ==1 ) %>% semi_join(selfies) %>%
  select(repository)

non_selfies <- all_repo_stars %>% anti_join(self_star1)
```

```{r}
not_selfies %>%
  filter( n < 100) %>%
  ggplot(aes(x = n)) + geom_histogram(binwidth=1, fill = "white", color = "black") +
  theme_bw() + base_theme() +
  labs(x = "Number of stars")
```

```{r}
n_distinct(non_selfies$n)
```

```{r}
write_lines()
```

